### PR TITLE
Create an Autofac Sample for WPF

### PR DESCRIPTION
**Pull request by karlfl**
Here's a contribution for the Samples repo.  If this looks good I'll make similar tweaks to show samples for the other DI containers.  I added "TODO" comments to help step the users through the initial steps of creating a Prism app.  The rest is a mirror of the HelloWorld app, only using Autofac instead of Unity.

### CODE REVIEW

**Comment by bartlannoeye** [comment]
Wondering if we should have a common library between the samples for all IoC containers to prevent too much duplicate code in views, viewmodels, ... 

When we want to expand our sample, it would be available to all configurations without too much effort. When I'm using Autofac, I'll only look at the Autofac sample and not e.g. the Unity sample which could be much more detailed.

**Comment by karlfl** [comment]
Intriguing thought.  Although don't some IoC containers use different conventions?  I think MEF (probably not a great IoC example) uses code attributes to define dependencies and even modules.  I've not done a lot with different IoC containers and Prism (primarily just Prism Unity).  Maybe Prism hides these differences, but I don't think so.  Right now these apps are extremely simple (shell and one module with one view/model).  Maybe if these become more robust samples then some leverage might be beneficial, but for now I think the "leveraging" might make them more complicated.. That's my two cents, FWIW :-).

**Comment by brianlagunas** [comment]
Maybe we should have subfolders under the Samples root to indicate the container the sample uses.  Something like:

Unity/
     HelloWorld
Autofac/
    HellowWorld
etc....

Thoughts?

**Comment by karlfl** [comment]
I like the idea of organizing the samples by folder.  It should make it easier for people to find a suitable sample for their needs.  If developers are working with Unity, then they would know where to look.  However, I think developers may search for samples based on Prism feature more than container type.   For example developers may look for how to implement Navigation or Eventing.  Those pieces are probably independent of container and we may not need a Unity example and an MEF example.  Just one container would suffice to help the user understand how to use the feature.  So if we want to place focus on Prism features, then I'd recommend we use a Feature/Container folder structure.

HelloWorld/Unity
HelloWorld/Autofac

Navigation/Unity
Eventing/Unity   

We may also want to pick a primary container (say Unity) for use in the samples and make sure that all samples are at least implemented well using that container.   Then as time permits, or volunteers contribute, we could expand into other containers for those samples.  The only exception is for the HelloWorld sample which I think we should make sure has samples for all containers Prism supports.

**Comment by bartlannoeye** [comment]
That's why I suggested to separate logic in a reusable library if you want to have your samples available for multiple containers. But this might make things too complex as mentioned above.

Picking one container as the default for all samples is a good idea, but then I would stick to that container and not even mention it. Maintaining every single sample for every possible container we support might be just too much work.
And use the HelloWorld sample to show how to use different IoC contaners.

IoC/Unity  (or Container/Unity as its a container)
IoC/Autofac

and all other samples are just
Navigation/Default
Navigation/CustomViewModelLocator
Eventing

**Comment by brianlagunas** [comment]
Unity will be our default container for our samples.  I do think it will be valuable to have a subfolder for samples that show the use of other containers.  I'll need to talk to @briannoyes before finalizing the structure.

**Comment by brianlagunas** [comment]
Can you update to the latest version of Prism and then I'll merge it.  Whenever I get time to think about a structure, I will rearrange it then.

**Pull request merged**
