### PR TITLE
Removes magic string of the view name.

### PR DESCRIPTION
**Pull request by phenixita**
Removes the magic string for the ViewA view.

### CODE REVIEW

**Comment by brianlagunas** [comment]
Thanks for the PR, but these samples are simply meant to show the concepts of Prism without introducing too much infrastructure.  This is overkill for this sample and adds another layer of complexity.  This is definitely how you would do it in a production app though.

**Comment by bartlannoeye** [comment]
Might be an idea to write a small chapter on in the documentation though? What do you think Brian?

**Comment by brianlagunas** [comment]
Probably not worth the time. We have much more important things to work on.

**Comment by phenixita** [comment]
This is in your official documentation http://prismlibrary.readthedocs.io/en/latest/WPF/07-Composing-the-UI/ 
screenshot_20170920-174723_01

**Comment by brianlagunas** [comment]
@phenixita Great find! You da man!

**Comment by phenixita** [comment]
:-)

**Pull request closed without merging**
