### PR TITLE
[DO-NOT-MERGE] [IN-PROGRESS] Update samples to .NET Core 3.1

### PR DESCRIPTION
**Pull request by seesharprun**
Addresses #64 

Trying to accomplish multiple objectives here:

-   Remove **AssemblyName** from sample projects

-   Add **readme.md** file to each project directory

-   Move project source code to **src** directory to match Xamarin samples

-   Updating projects to **.NET Core 3.1 (LTS)**

-   Moving Prism package versions to **Directory.Build.props** file

-   Adding instructions to run samples in **Visual Studio** and **.NET CLI**

### CODE REVIEW

**Comment by brianlagunas** [comment]
Please do not rename the folders to src.

**Comment by seesharprun** [comment]
I was emulating: https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/01-HelloPrism

Do you still want the readme.md?

**Comment by brianlagunas** [comment]
The solution structure for an XF app is different than a WPF app, so no need to rename the solution folders to src. Feel free to add the readme file.

**Comment by seesharprun** [comment]
I removed the src folders.

FYI: the src folder is completely irrelevant to how a Xamarin Forms app works: https://github.com/xamarin/xamarin-forms-samples/tree/master/Todo. It's just a matter of what the SLN file (only relevant to Visual Studio) is pointing to.

I was just mirroring the style of the more recent samples repo

**Comment by brianlagunas** [comment]
It is relevant to how we structure them in Prism. The WPF samples repo takes the default Visual Studio behavior when creating a new solution. Dan did his own thing in the XF samples repo.

**Comment by seesharprun** [comment]
Ah! That makes sense. You are structuring the projects based on the Visual Studio templates.

**Comment by seesharprun** [comment]
Another FYI: The 07 demos may not work outside of Visual Studio.

Two issues:
-    The ``$(SolutionDir)`` and ``$(SolutionName)`` variables won't resolve in the .NET CLI unless you build from the solution level
-    Building at the solution level will still cause a silent failure

In the interest of moving forward, I would recommend that I just drop the .NET CLI build instructions from the 07 demos

**Comment by dansiegel** [comment]
So the variable should actually be just PrismVersion here not PrismUnityVersion. When you go through the samples remember that some projects in some of the samples do not reference Prism.Unity. Some reference Prism.Wpf or Prism.Core.

While I see it's already been reverted keep in mind that the Xamarin.Forms samples were completely redone from the ground up. That is not something we are looking at or is there any reason for us to do for WPF. 

> The $(SolutionDir) and $(SolutionName) variables won't resolve in the .NET CLI unless you build from the solution level

Add this as the Directory.Build.props in the root (next to the sln file) of the sample... making the required changes to the SolutionName and path to the root Directory.Build.props.
```xml
<Project>
  <PropertyGroup>
    <SolutionDir Condition=" $(SolutionDir) == '' ">$(MSBuildThisFileDirectory)</SolutionDir>
    <SolutionName Condition=" $(SolutionName) == '' ">WhateverTheSolutionNameIs</SolutionName>
  </PropertyGroup>

  <Project Import="../PathToRoot/Directory.Build.props" />
</Project>
```

**Comment by seesharprun** [comment]
I haven’t forgotten about this. Just got a family sick with the flu and some competing priorities. Will be back on this next week.

**Comment by brianlagunas** [comment]
Closing as stale

**Pull request closed without merging**
